2022-02-09 14:50:55,861 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-09 14:51:03,712 ERROR: Exception on /editschedule/1 [GET] [in c:\led-lights\webapp\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
TypeError: editschedule() missing 1 required positional argument: 'day'
2022-02-10 14:27:17,722 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-10 14:37:35,771 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-10 14:42:33,097 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-10 14:46:55,015 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-10 14:47:50,392 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-10 14:50:20,049 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-10 14:55:13,511 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-10 15:07:02,299 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-11 14:19:47,164 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-11 14:20:22,863 ERROR: Exception on /editschedule/1 [GET] [in c:\led-lights\webapp\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Led-Lights\webapp\app\routes.py", line 284, in editschedule
    currentScene = dataDict[id]
TypeError: list indices must be integers or slices, not str
2022-02-11 14:21:18,483 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-11 14:21:49,445 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-11 14:23:13,763 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-11 14:25:06,842 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-11 14:27:22,640 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-11 14:33:53,137 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-11 14:36:01,824 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-11 14:56:16,080 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-11 14:56:30,127 ERROR: Exception on /editschedule/1 [POST] [in c:\led-lights\webapp\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Led-Lights\webapp\app\routes.py", line 313, in editschedule
    "start_time": "1900-01-01T" + start_time + ":00.000"}
TypeError: can only concatenate str (not "datetime.time") to str
2022-02-11 14:59:20,996 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-11 14:59:31,224 ERROR: Exception on /index [GET] [in c:\led-lights\webapp\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Led-Lights\webapp\app\routes.py", line 120, in index
    sch_date = datetime.datetime.strptime(i["start_time"], '%Y-%m-%dT%H:%M:%S.%f')
  File "C:\Program Files (x86)\Python37-32\lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Program Files (x86)\Python37-32\lib\_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '1900-01-01T07:39:00:00.000' does not match format '%Y-%m-%dT%H:%M:%S.%f'
2022-02-14 14:52:52,801 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
2022-02-14 14:53:03,933 ERROR: Exception on / [GET] [in c:\led-lights\webapp\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Led-Lights\webapp\app\routes.py", line 120, in index
    sch_date = datetime.datetime.strptime(i["start_time"], '%Y-%m-%dT%H:%M:%S.%f')
  File "C:\Program Files (x86)\Python37-32\lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Program Files (x86)\Python37-32\lib\_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '1900-01-01T07:39:00:00.000' does not match format '%Y-%m-%dT%H:%M:%S.%f'
2022-02-14 14:53:51,272 INFO: WebApp startup [in C:\Led-Lights\webapp\app\__init__.py:45]
